library(tidyverse)
source("./syntax/project_functions.R")

sncs_orig <- haven::read_spss("./data/seattle/raw/sncs_survey.sav")

sncs_indiv <- sncs_orig %>%
  select(TRACT                           = tract,
         COHTR_help                         = q19d,
         COHTR_trust                        = q19b,
         INF_skip                           = q20a,
         INF_disrespect                     = q20c,
         INF_fight                          = q20d,
         INF_graffiti                       = q20b,
         INF_fight_2                        = q78,
         INF_ob_skip                        = q15d,
         INF_ob_disrespect                  = q15c,
         INF_ob_fight                       = q15a,
         INF_ob_graffiti                    = q15b,
         EXCH_favor                         = q10b,
         EXCH_watch                         = q10a,
         EXCH_ask                           = q10e,
         EXCH_activities                    = q10h,
         EXCH_eat                           = q10c,
         EXCH_problem                       = q10d,
         EXCH_stop_chat                     = q10f,
         CLOSE_watch                        = q19a,
         CLOSE_know                         = q19c,
         SOCDIS_teens                       = q14a,
         SOCDIS_loud                        = q14e,
         PHYDIS_litter                      = q14b,
         PHYDIS_graffiti                    = q14c,
         PHYDIS_vacant                      = q14d,
         ATTACH_miss                        = q7,
         ATTACH_moving                      = q5,
         ATTACH_move5yr                     = q6,
         TIES_relatives                     = q8a,
         TIES_friends                       = q8b,
         INTERVENE_noise                    = q12,
         VICT_viol_ev                       = violvict,
         VICT_viol_2                        = violvic2,
         VICT_prop_ev                       = propvict,
         VICT_prop_2                        = propvic2,
         RACE                               = racecat,
         ORGS_church                        = q13a,
         ORGS_recreation                    = q13b,
         ORGS_charity                       = q13c,
         ORGS_ethnic                        = q13d,
         ORGS_neighborhood                  = q13e,
         ORGS_other                         = q14a,
         PERC_EFF_small_groups              = q16a,
         PERC_EFF_neighb_assoc              = q16b,
         PERC_EFF_police                    = q16c,
         PERC_EFF_government                = q16d,
         PERC_EFF_self                      = q16e,
         PERC_RACE_white                    = q17a,
         PERC_RACE_asian                    = q17b,
         PERC_RACE_black                    = q17c,
         PERC_RACE_hispanic                 = q17d,
         RACE_mingle                        = q18a,
         RACE_trust                         = q18b,
         RACE_tension                       = q18c,
         COTS_turn_cheek                    = q21a,
         COTS_SELF_avoid_conflict           = q21b,
         COTS_SELF_violence_justified       = q21c,
         COTS_SELF_child_avoid_conflict     = q21d,
         COTS_SELF_okay_break_law           = q21e,
         COTS_SELF_tough_rep                = q21f,
         COTS_NEIGHBS_youth_fight_respect   = q22a,
         COTS_NEIGHBS_disrespect_retaliate  = q22b,
         COTS_NEIGHBS_gun_respect           = q22c,
         COTS_NEIGHBS_crime_necessary       = q22d,
         COTS_NEIGHBS_kids_taught_fight     = q22e,
         COTS_NEIGHBS_tough_image           = q22f,
         PERC_WRONG_smoking                 = q23a,
         PERC_WRONG_marijuana               = q23b,
         PERC_WRONG_alcohol                 = q23c,
         PERC_WRONG_fighting                = q23d,
         STRAIN_rich_oppress_poor           = q24a,
         STRAIN_wrongful_accuse             = q24b,
         STRAIN_hard_work                   = q24c,
         STRAIN_race_crime                  = q24d,
         STRAIN_race_fair                   = q24e,
         POLICE_good_job_neighb             = q25a,
         POLICE_racial_profiling            = q25b,
         POLICE_hassle                      = q25c,
         POLICE_seen_month                  = q26,
         POLICE_treat_poor                  = q27,
         POLICE_treat_black                 = q28,
         POLICE_treat_asian                 = q29,
         POLICE_treat_hispanic              = q30,
         POLICE_treat_foreign               = q31,
         PERC_RACE_white_drugs_gangs        = q32a,
         PERC_RACE_asian_drugs_gangs        = q32b,
         PERC_RACE_black_drugs_gangs        = q32c,
         PERC_RACE_hispanic_drugs_gangs     = q32d,
         RACE_PREF_quarter_white            = q33a,
         RACE_PREF_quarter_asian            = q33b,
         RACE_PREF_quarter_black            = q33c,
         RACE_PREF_quarter_hispanic         = q33d,
         FOREIGN_BORN                       = q35,
         CRIME_self_report                  = q21g,
         SES                                = ses,
         SEX                                = qdem3,
         MARRIAGE                           = married,
         NCHILDREN                          = child,
         AGE                                = age,
         MOVES                              = q4,
         HOMEOWN                            = q2,
         YRSATADDRESS                       = length,
         SAMPLE                             = sample,
         CASEID                             = caseid,
         POLICE_block_activity              = q10g,
         STRANGERS_tell_from_resident       = q49,
         STRANGERS_first_name_basis         = q50,
         Talk_with_neighbs_crime            = q51,
         VICT_prop_2_reported               = q56e,
         VICT_threat_2                      = q57b,
         VICT_threat_2_reported             = q57e,
         VICT_viol_2_reported               = q58e,
         VICT_any_househld                  = q59,
         VICT_illegal_entry_ev              = q60b,
         VICT_illegal_entry_2               = q60b,
         VICT_illegal_entry_reported        = q60d,
         VICT_theft_ev                      = q61a,
         VICT_theft_2                       = q61b,
         VICT_theft_reported                = q61e,
         VICT_car_ev                        = q62a,
         VICT_car_2                         = q62b,
         VICT_car_reported                  = q62e,
         VICT_robbery_ev                    = q63a,
         VICT_robbery_2                     = q63b,
         VICT_robbery_reported              = q63e,
         RES_property_value                 = q73,
         RES_rent                           = q74,
         BE_school_3_blocks                 = q66a,
         BE_bar_3_blocks                    = q66b,
         BE_park_3_blocks                   = q66c,   
         BE_shopping_3_blocks               = q66d,   
         BE_hotel_3_blocks                  = q66e,   
         BE_busstop_3_blocks                = q66f,
         FEAR_safe_neighb                   = q54,
         FEAR_worry_attack                  = q52,  
         FEAR_worry_breakin                 = q53, 
         FEAR_for_self                      = q55a,
         FEAR_for_partner                   = q55b,
         FEAR_oldest_son                    = q55c,
         FEAR_oldest_daughter               = q55d,     
         RISK_unocc_home_night_week         = q67,     
         RISK_unocc_home_day_week           = q68,
         RISK_visit_bar_week                = q69,     
         PREC_lights_on_now                 = q64a,
         PREC_in_neighb_watch_now           = q64f,
         PREC_extra_locks_now               = q64b,
         PREC_burglar_alarm_now             = q64c, 
         PREC_dog_now                       = q64d, 
         PREC_home_weapon_now               = q64e,
         PREC_own_gun                       = q65,
         RES_house_type_recode              = q1, 
         RES_live_alone                     = qho1,
         RES_people_in_home                 = qho2
         ) %>%
  mutate(SAMPLE = as_factor(SAMPLE)) %>%
  filter(!is.na(TRACT)) %>%
  mutate(NCHILDREN=if_else(as.numeric(NCHILDREN)==99, as.numeric(NA), NCHILDREN)) %>% 
  mutate_at(vars(SEX, RACE, HOMEOWN), as_factor) %>%
  mutate(FEMALE           = if_else(SEX=="Female",1,0),
         Asian            = if_else(RACE=="NH Asian/PI", 1, 0),
         African_American = if_else(RACE=="NH Black", 1, 0),
         Hispanic         = if_else(RACE=="Hispanic", 1, 0),
         Homeowner        = if_else(HOMEOWN=="Own or Buying",1,0),
         N_Moves          = as.numeric(MOVES)
  ) %>%
  mutate(across(matches("COHTR|ISC|EXCH|CLOSE|SOCDIS|PHYDIS|ATTACH|TIES|INTERVENE|ORGS|PERC_EFF|COTS|PERC_WRONG|STRAIN|POLICE|RACE"), ~ordered(as_factor(.)) )) %>%
  # mutate(across(matches("BE_|VICT"), ~as_factor(.))) %>%
  rename(TRACT_2000 = TRACT) %>%
  mutate(TRACT_1980 = paste0(str_sub(TRACT_2000, 1, -3), "00"))

save(sncs_indiv, file="./data/seattle/derived/sncs_indiv.RData")
