library(tidyverse)
source("./syntax/project_functions.R")

miethe_orig <- haven::read_spss("./data/raw/miethe_survey.sav")

miethe_indiv <- miethe_orig %>%
  select(TRACT,
         EXCH_favor                         = Q83,
         EXCH_watch                         = Q82,
         EXCH_problem                       = Q85,
         EXCH_eat                           = Q84,
         ORGS_neighborhood                  = Q86,
         EXCH_watch_now                     = Q124,
         EXCH_watch_2yrsago                 = Q125,
         CLOSE_recognize                    = Q79,
         CLOSE_know                         = Q81,
         SOCDIS_teens                       = Q92,
         PHYDIS_litter                      = Q93,
         PHYDIS_graffiti                    = Q96,
         PHYDIS_vacant                      = Q94,
         VICT_assault_2                     = Q36,
         VICT_robb_2                        = Q50,
         VICT_burg_2                        = Q16,
         VICT_theft_2                       = Q33,
         RACE                               = Q178,
         SES_income                         = Q215,
         SES_education                      = Q179,
         SEX                                = Q12,
         MARRIAGE                           = Q180,
         AGE                                = AGE,
         HOMEOWN                            = Q194,
         YRSINNEIGHB                        = YEARS,
         NCHILDREN                          = Q177,
         BE_school_3_blocks                 = Q67,
         BE_store_3_blocks                  = Q68,
         BE_bar_3_blocks                    = Q69,
         BE_fastfood_3_blocks               = Q70,
         BE_bank_office_3_blocks            = Q71,
         BE_park_3_blocks                   = Q72,
         BE_shopping_3_blocks               = Q73,
         BE_hotel_3_blocks                  = Q74,
         BE_busstop_3_blocks                = Q75,
         ATTACH_move_5_yrs                  = Q78,
         TIES_block                         = Q80,
         POLICE_block_activity              = Q87,
         POLICE_seen_n_week                 = Q91,
         BE_poor_streetlights_3_blocks      = Q95,
         FEAR_place_afraid_night_3_blocks   = Q76,
         FEAR_safe_neighb                   = Q77,
         FEAR_felt_danger_month             = Q105,
         FEAR_worry_attack                  = Q166,
         FEAR_worry_breakin                 = Q167,
         FRIEND_VICTIMIZED                  = Q168,
         RISK_evenings_out_week             = Q98,
         RISK_eves_out_2_years              = Q169,
         RISK_walk_night_week               = Q99,
         RISK_unocc_home_night_week         = Q100,
         RISK_unocc_home_day_week           = Q101,
         RISK_unocc_home_day_2_years        = Q170,
         RISK_away_home_hrs_week            = Q102,
         RISK_visit_bar_week                = Q103,
         RISK_street_teens_week             = Q104,
         RISK_shop_alone                    = Q151,
         RISK_physical_size                 = Q154,
         RISK_can_defend_self               = Q155,
         RISK_new_places_days_month         = Q106,
         RISK_use_transit                   = Q107,
         RISK_use_transit_n_month           = Q108,
         RISK_in_crowded_place_month        = Q161,
         RISK_carried_50_month              = Q164,
         RISK_wear_jewelry                  = Q165,
         RISK_shop_fixed_time               = Q203,
         PREC_lock_doors_now                = Q110,
         PREC_lock_doors_2_years            = Q111,
         PREC_lights_on_now                 = Q112,
         PREC_lights_on_2_years             = Q113,
         PREC_in_neighb_watch_now           = Q114,
         PREC_in_neighb_watch_2_years       = Q115,
         PREC_extra_locks_now               = Q116,
         PREC_extra_locks_2_years           = Q117,
         PREC_carry_weapon_now              = Q118,
         PREC_carry_weapon_2_years          = Q119,
         PREC_burglar_alarm_now             = Q120,
         PREC_burglar_alarm_2_years         = Q121,
         PREC_dog_now                       = Q122,
         PREC_dog_2_years                   = Q123,
         PREC_home_weapon_now               = Q126,
         PREC_home_weapon_2_years           = Q127,
         PREC_increased_precautions_2_years = Q128,
         PREC_changed_activities_2_years    = Q129,
         PREC_check_wallet                  = Q207,
         PREC_look_for_susp_people          = Q208,
         PREC_avoid_eye_contact             = Q209,
         PREC_walk_faster                   = Q210,
         PREC_distance_strangers            = Q211,
         RES_ground_windows                 = Q134,
         RES_tall_fence                     = Q135,
         RES_vacant_nearby                  = Q136,
         RES_corner_house                   = Q140,
         RES_on_alley                       = Q141,
         RES_street_type                    = Q145,
         RES_trees_front                    = Q146,
         RES_difficult_breakin              = Q150,
         RES_unit_type                      = Q195,
         RES_house_type                     = Q9,
         RES_house_type_recode               = Q10,
         RES_n_units                        = Q197,
         RES_floor                          = Q198,
         RES_n_floors                       = Q199,
         RES_people_in_home                 = Q175,
         RES_adults_in_home                 = Q176,
         RES_distance_to_work               = Q190,
         OWN_portable_tv                    = Q156,
         OWN_vcr                            = Q157,
         OWN_camera                         = Q158,
         OWN_computer                       = Q159,
         OWN_bike_motorcycle                = Q160,
         OWN_car                            = Q201,
         MILES_DRIVEN_week                  = Q202,
         WORK_public_contact                = Q191,
         WORK_handle_money                  = Q192,
         WORK_schedule                      = Q193
         ) %>%
  filter(!is.na(TRACT)) %>%
  mutate_at(vars(starts_with("EXCH"), contains("DIS"), CLOSE_recognize), ~if_else(.==1, 1, 0)) %>%
  mutate_at(vars(RACE, SEX, MARRIAGE, HOMEOWN, 
                 VICT_assault_2, VICT_robb_2, VICT_theft_2, VICT_burg_2), 
            as_factor) %>%
  mutate(TRACT_1980            = TRACT*100,
         CLOSE_know       = (5-as.numeric(CLOSE_know)),    
         African_American = if_else(RACE=="BLACK",1,0),
         Other_Race       = if_else(RACE=="OTHER",1,0),
         FEMALE           = if_else(SEX=="FEMALE",1,0),
         MARRIAGE         = if_else(MARRIAGE=="MARRIED/COHAB",1,0),
         SES_income       = as.numeric(SES_income),
         SES_education    = as.numeric(SES_education),
         Homeowner        = if_else(HOMEOWN=="OWN",1, 0),
         AGE              = as.numeric(AGE),
         YRSINNEIGHB      = as.numeric(YRSINNEIGHB)/10,
         VICT_assault_2   = if_else(VICT_assault_2=="YES", 1, 0),
         VICT_robb_2      = if_else(VICT_robb_2=="YES", 1, 0),
         VICT_theft_2     = if_else(VICT_theft_2=="YES", 1, 0),
         VICT_burg_2      = if_else(VICT_burg_2=="YES", 1, 0),
         NCHILDREN        = as.numeric(NCHILDREN)) %>%
  mutate(VICT_viol_2      = if_else(VICT_assault_2==1 | VICT_robb_2==1, 1, 0),
         VICT_prop_2      = if_else(VICT_burg_2==1 | VICT_theft_2==1, 1, 0)) %>%
  select(-RACE, -SEX) %>%
  mutate_at(vars(starts_with("EXCH"), starts_with("CLOSE"), starts_with("PHYDIS"),
                 starts_with("SOCDIS"), starts_with("VICT"), MARRIAGE, Homeowner,
                 African_American, Other_Race, FEMALE), ordered)

save(miethe_indiv, file="./data/derived/miethe_indiv.RData")
