# A Situational Theory of Neighborhood Crime {#theory}

## Introduction

This chapter proposes an integrative theory that links social structural explanations of neighborhood crime—collective efficacy and broken windows—to opportunity-based explanations for crime—routine activities. This first chapter serves two purposes: In the first half, I present a comprehensive overview of the key theories used in this dissertation, and, in the second half, I propose a situational micro-foundation based on social interaction that links these theories into a multilevel criminal opportunity framework. 

The first half begins by describing collective efficacy and broken windows theories in terms of their causal mechanisms. While both theories operate at the macro-level, they rely on individual perceptions as mediating micro-level mechanisms. Neither, however, features a fully-articulated theory of individuals or the situations in which crime occurs. I then introduce routine activities theory, which describes crime as the result of convergences of individuals and objects fitting abstract crime-relevant roles. This language is useful for connecting collective efficacy and broken windows and introducing aspects of criminal opportunity neglected by collective efficacy and broken windows. While a powerful tool for analyzing macro-level variation in crime, routine activities also features an incomplete theory of individuals and the situation which limits its utility for analyses at smaller scales. I argue that linking these social structural theories together provides a more complete theory of neighborhood crime, but doing so requires a fully-articulated micro-theory of the situation.

In the second half of the chapter, I use a pragmatist micro-theory to elaborate a situational foundation for these theories based on roles and perception [@matsuedaMicroTheoryCrime2021]. This situational foundation links collective efficacy, broken windows, and routine activities into a framework that explains how the social structural characteristics and physical environment of neighborhoods are related to the distribution of roles in space and time. I also consider how individuals and groups work to alter these distributions and their determinants, and how the outcomes of situations contribute to changes in social structure and the physical environment by altering shared meanings. While the social structural theories under consideration presently have unarticulated or incomplete micro-level mechanisms, this situational explanation provides explicit social mechanisms compatible with their core claims and existing empirical evidence. I conclude with empirical implications for studies of neighborhood crime.

## Collective Efficacy

Collective efficacy is conceptualized as a neighborhood capacity for achieving a common goal—typically one which cannot be accomplished without collective action [@sampsonNeighborhoodsViolentCrime1997a]. Intellectually rooted in social disorganization theory, Sampson and colleagues’ collective efficacy theory posits that a major source of neighborhood variation in crime rates is the differential capacity of neighborhoods to produce social control [@sampsonNeighborhoodsViolentCrime1997a]. Following Janowitz [-@janowitzSociologicalTheorySocial1975], they define social control as the capacity of a group to regulate its members’ behavior to realize collective goals, such as maintaining a safe environment.^[Collective efficacy theory assumes consensus in normative goals (living in an area free of crime), but variation in regulatory capacity (social control). This echoes the value assumptions of social disorganization reformulations based on control theory [@bursikNeighborhoodsCrimeDimensions1993; @kornhauserSocialSourcesDelinquency1978].] For the purpose of controlling crime and disorder, collective efficacy represents a process through which latent social capital resources—such as norms, trust, and cohesion—are translated into action—resident interventions against deviance.

Sampson [-@sampsonGreatAmericanCity2012, p. 182] describes collective efficacy as an emergent property of neighborhood social structure, rather than the simple aggregation of the abilities of members to accomplish the task in question. It is characterized by an arrangement of social capital which facilitates collective goal-oriented actions. Specifically, collective efficacy for the task of social control consists of an additive combination of perceived trust and cohesion combined with expectations that neighbors will engage in acts of informal social control, such as surveillance or sanctioning. This is based on claim that "the collective willingness to intervene in the neighborhood is enhanced under conditions of mutual trust and cohesion," [@sampsonSystematicSocialObservation1999, p. 620]. This suggests, however, that trust and cohesion may either precede expectations for intervention or moderate their relationship with crime rather than exhibit an additive relationship as is commonly specified [@hippCollectiveEfficacyHow2016].

While collective efficacy is most often examined in the context of crime, in particular violence, collective efficacy is conceived of as a general capacity for achieving community goals through collective action [@sampsonNeighborhoodsViolentCrime1997a; @sampsonGreatAmericanCity2012]. Consequently, it has been used to explain a variety of outcomes at the neighborhood level—prosocial behavior, domestic violence, birth weight, asthma [@sampsonGreatAmericanCity2012, p. 160]. This mirrors Shaw & McKay’s [-@shawJuvenileDelinquencyUrban1942] original social disorganization research which recognized urban social problems of many forms cluster together because they are the result of the same structural disadvantages.  It is theorized that different forms of social capital facilitate different actions, and thus different indicators might be used to operationalize collective efficacy for other purposes [@wickesCollectiveEfficacyTask2013].

### Sources of Collective Efficacy

Rooted in the social disorganization tradition, the sociodemographic structure of neighborhoods is assumed to be a fundamental source of collective efficacy. Concentrated disadvantage, residential instability, and, to a lesser degree, racial/ethnic heterogeneity and immigration inhibit collective efficacy by depriving the community of resources, disrupting social ties, and impeding the realization of common values [@sampsonNeighborhoodsViolentCrime1997a; @sampsonGreatAmericanCity2012]. 

Social network ties and local organizations have been suggested as the primary mediators between sociodemographic structure and collective efficacy. These are believed to operate by producing social capital or providing social structures which can be mobilized to facilitate social control [@sampsonGreatAmericanCity2012, pp. 157-158]. For example, collective efficacy appears to be promoted by density of intimate ties [@morenoffNeighborhoodInequalityCollective2001] and reciprocated exchange [@sampsonSystematicSocialObservation1999]. Complicating this story, however, is evidence that reciprocated exchange also moderates collective efficacy, attenuating its negative relationship with crime [@browningIlluminatingDownsideSocial2009]. Collective efficacy is, however, primarily about the content of social relations (e.g. trust, norms) rather than the structure of networks (e.g. ties) [@sampsonGreatAmericanCity2012, p. 45]. This stands in contrast with earlier social disorganization formulations which emphasized social structures of neighborhoods—institutions, organizations, and ties [@shawJuvenileDelinquencyUrban1942; @bursikNeighborhoodsCrimeDimensions1993]. Certain social structures and resources support (or inhibit) the development of collective efficacy, but they are not sufficient alone to prevent crime and no particular arrangement—such as a dense web of intimate ties—is assumed necessary to prevent crime. What is key is that the social structure can support cohesion and trust and expectations for social control.

Finally, collective efficacy also appears to be the result of a number of feedback processes. First, collective efficacy exhibits a reciprocal relationship with crime: it both suppresses and is suppressed by crime [@sampsonGreatAmericanCity2012]. The literature suggests this occurs over time within neighborhoods through two mechanisms. First, at the individual level, residents update their expectations for the social control behavior of their neighbors based on crime and disorder they observe [@hippCollectiveEfficacyHow2016; @matsuedaMeasuringCollectiveEfficacy2016]. Second, crime increases fear of crime and perceived likelihood of victimization. In response, residents constrain their social behavior to reduce the risk of victimization, which reduces social interaction and monitoring, resulting in weakened social control capacity [@bellairInformalSurveillanceStreet2000; @liskaFunctionsCrimeParadoxical1991; @markowitzExtendingSocialDisorganization2001; @sampsonSystematicSocialObservation1999]. This feedback appears weaker than either the effect of collective efficacy on crime [@sampsonSystematicSocialObservation1999; @sampsonGreatAmericanCity2012].

Collective efficacy, both directly and via structural features, is also influenced by conditions in nearby neighborhoods and city-wide processes. Structural disadvantage and crime are highly concentrated in space [@petersonDivergentSocialWorlds2010]. Proximity to concentrations of disadvantage and crime causes spillovers to nearby neighborhood even with little local sources of crime. Similarly, high collective efficacy appears to exhibit spillover effects, reducing crime in nearby areas [@sampsonGreatAmericanCity2012]. Taken together, this means collective efficacy tends to concentrate in particular areas, spatially reproducing itself. Taken together, these feedback processes explain why collective efficacy manifests high stability over time: as a general problem-solving capacity, it combats destabilization of antecedents within the neighborhood or in nearby areas.

### Mechanisms for Collective Efficacy

Sampson and colleagues suggest collective efficacy inhibits disorder and minor deviance through both external and internal mechanisms of informal social control [@sampsonGreatAmericanCity2012; @sampsonNeighborhoodsViolentCrime1997a]. In the external mechanism, residents directly intervene against norm violations—such as by verbally sanctioning. In the internal mechanism, the deviant behavior of actors is inhibited by their internalization of local norms or through deterrence by increasing expectations that residents will directly sanction them. This combination of internal and external mechanisms is common to social disorganization models based on control theory [@bursikNeighborhoodsCrimeDimensions1993; @kornhauserSocialSourcesDelinquency1978]. Collective efficacy is assumed to inhibit more serious crime through these mechanisms as well, but also through an indirect external mechanism in which the direct social control interventions of residents remove contexts that give rise to serious crime—such as unsupervised peer groups [@maimonUnstructuredSocializingCollective2010; @sampsonNeighborhoodsViolentCrime1997a, p. 918]. 

Collective efficacy is also assumed to predict reporting crimes to police [@sampsonSystematicSocialObservation1999, p. 612; @sampsonGreatAmericanCity2012, p. 152], though most research in this area de-emphasizes this mechanism, does not use calling police as an indicator for the efficacy, and does not estimate efficacy’s relationship to calling police. If collective efficacy predicts calls for police service, this may operate in a fashion analogous to the primary internal and external informal control mechanisms, but with police as the sanctioning actors invoked by residents—that is, a formal control mechanism. Chapter \@ref(formalcontrol) of this dissertation examines this alternate formal social control pathway, arguing it should be separated from the informal control pathway. 

Similarly, collective efficacy is assumed to predict efforts to influence local government, such as organizing a referendum to shut down a problematic bar or petitioning housing authorities demolish a house used as a drug venue [@sampsonSystematicSocialObservation1999, p. 612]. This mechanism is captured by common indicators of collective efficacy, unlike for contacting police, by asking respondents how likely it would be for their neighbors to organize to protect a fire station (or library) threatened with closure [@earlsProjectHumanDevelopment1999; @houseChicagoCommunityAdult2011]. Chapter \@ref(builtenvironment) of this dissertation examines the relationship between collective efficacy and differences in the built environment, proposing influence over local government as a mechanism.

Collective efficacy is thus theorized to promote resident actions of any kind which further the goal of reducing crime and disorder, whether intervening personally, calling police, complaining to public agencies, or organizing politically. In this way, as @sampsonSystematicSocialObservation1999 note, collective efficacy evokes the systemic model of social control [@bursikNeighborhoodsCrimeDimensions1993; @d03d980337c440b9bca544e58a37d424], by "recogniz[ing] the articulation among the private (family), parochial (neighborhood), and formal (public) orders but stresses the agency of residents in establishing these connections." That is, collective efficacy captures the capacity for neighborhoods to activate any mechanism of social control. This suggests that, rather than a "pure" theory of informal social control, collective efficacy is a general theory of collective action for social control. This perspective emphasizes conditions necessary for collective action over the form of action taken: a collective effort is required regardless of how social control is maintained.

This perspective deemphasizes, however, the systemic model of social control’s emphasis on articulation between levels, despite empirical evidence of interactions between collective efficacy (focusing on informal control) and perceptions of police efficacy (formal control) [e.g. @silverSourcesInformalSocial2004 and @drakulichRolePerceptionsPolice2013]. Sampson [-@sampsonGreatAmericanCity2012, p. 167] has suggested that perhaps in contexts where police and government are corrupt or ineffective and interventions are particularly dangerous, collective efficacy may promote survival rather than control of crime and deviance . This further suggests an interaction between resident capacities for collective action and their institutional context, one which may be relevant not just outside the United States, but perhaps also in American neighborhoods where residents perceive police and local government as illegitimate or hostile.

Importantly, collective efficacy does not appear to reduce criminal motivation of residents, as self-reported offending by youth is unrelated to the level of collective efficacy in their neighborhood of residence [@sampsonSocialAnatomyRacial2005].  This suggests collective efficacy reduces offending by regulating behavior situationally—restraining crime by residents and non-residents alike, but only in the focal neighborhood—rather than by reducing stable motivation—which would presumably inhibit crime only by residents, but would do so wherever they travel. This is further supported by evidence that neighborhood collective efficacy is negatively related to offending behavior of non-resident robbery offenders [@bernascoWhereOffendersChoose2009] and crime-prone youth [@wikstromActivityFieldsDynamics2010]. This implies a different role for collective efficacy than is suggested by Janowitz’s [-@janowitzSociologicalTheorySocial1975] definition of social control as the capacity to regulate group-member behavior. Collective efficacy appears to regulate both member and non-member (i.e. non-resident) behavior within the neighborhood, but does not regulate member behavior outside the neighborhood. This also sits in contrast to Shaw & McKay’s [-@shawJuvenileDelinquencyUrban1942] original social disorganization study in which they analyzed the spatial distribution of residences of juvenile delinquents—emphasizing the conditions that promote participation in delinquency—rather than the locations where delinquents commit crime. In this way, collective efficacy theory appears to speaks to where and how often offending occurs but not how individuals become involved in crime.

The diversity of proposed mechanisms for collective efficacy highlights their ad hoc and empirically-driven nature. Collective efficacy is typically presented as a macro-level theory, but crime is a situational phenomenon, the outcome of a situation. To explain their empirical findings, researchers speculate at cross-level and micro-level mechanisms that might plausibly link collective efficacy to criminal situations. These mechanisms are organized around no unifying micro-level theory, whether at the individual level or the situation level, and the mechanisms are typically not observed, tested, or used to make predictions—they make sense of empirical observations rather than explain them [@wattsCommonSenseSociological2014]. The present chapter undertakes the task of specifying a situational explanation for collective efficacy and other social structural theories of neighborhood crime, one which generates testable propositions.  Before specifying this explanation, I summarize broken windows, a theory of neighborhood crime which articulates some micro-mechanisms and is often presented as a competing explanation for crime to collective efficacy [@lanfearBrokenWindowsInformal2020].

## Broken Windows

The broken windows model describes neighborhoods as a system in which crime, disorder, and social control are reciprocally related [@wilsonBrokenWindows1982]. Disorder increases crime by signaling to potential offenders that the likelihood of residents intervening against them is low. Disorder also increases crime by signaling to residents that the neighborhood is unsafe, resulting in withdrawal from public spaces and subsequent reduction in social control capacity. Then, "Such an area is vulnerable to criminal invasion. Though it is not inevitable, it is more likely that here, rather than in places where people are confident they can regulate public behavior by informal controls…" [@wilsonBrokenWindows1982, p. 3]. If this reduced social control capacity results in large increases in crime, withdrawal from public spaces turns to departure from the neighborhood—except for "the poorest or those who are blocked by racial prejudice"—resulting in the concentration of disadvantage and collapse of social control.

Because of feedback loops in the model, sudden changes that overwhelm the social control capacity of a neighborhood can result in a cascade of rapidly increasing crime and disorder and decreasing social control. The presence of this threshold—which separates stable neighborhoods from those in a "spiral of decay," [@skoganDisorderDeclineCrime1990]—is an underappreciated feature of the broken windows model. @wilsonBrokenWindows1982 state most neighborhoods exist in an equilibrium state where disorder is managed by informal controls, and they have sufficient surplus informal control capacity to address sudden challenges as they arise. This is a negative or balancing feedback loop which maintains system stability. However, if disorder exceeds some threshold and overwhelms the neighborhood’s informal control capacity, residents begin to withdraw from public spaces and informal control recedes. Once this occurs, the neighborhood enters a disequilibrium state as the feedback loop becomes positive or explosive. Social control capacity will fall and crime will rise, and withdrawal will escalate to outmigration. Absent a stabilizing exogenous intervention, the neighborhood eventually enters a new absorbing equilibrium, a collapsed state "where the situation is hopeless," [@wilsonBrokenWindows1982, p. 8].

### Sources of Informal Social Control in Broken Windows

@wilsonBrokenWindows1982 suggest the ability and willingness of residents to regulate public space is rooted in two proximate factors: (1) surveillance and sanctioning capability provided by the presence of residents in public places and (2) attachment to the neighborhood and a commensurate sense of responsibility for enforcing its norms. The first case is essentially Jacobs’s [-@jacobsDeathLifeGreat1992] "eyes on the street": informal control alone is sufficient to regulate an area when there are many potential monitors or, as Wilson & Kelling [-@wilsonBrokenWindows1982, p. 7] write, "the ratio of respectable to disreputable people" is high. In the second case, @wilsonBrokenWindows1982 state people more likely to intervene where they feel responsibility for the community, and feeling responsibility is rooted in the perception that one is a member of the community. This evokes the cohesion and trust component of collective efficacy.

Police—the focus of the original in *The Atlantic*—do not directly provide informal social control but serve a supportive role: "The essence of the police role in maintaining order is to reinforce the informal control mechanisms of the community itself," [@wilsonBrokenWindows1982, p. 5]. While most social control is exerted directly by residents, they may also turn to police to resolve situations, particularly when attempts at informal social control are rebuffed. Wilson and Kelling describe two elements of the policing role which enable to them to bolster informal control: their formal role and corresponding capacity for force. First, police officers occupy a formal role that obligates them to address problems they observe or have brought to their attention by residents. That is, their feeling of responsibility to act is imposed by their role rather than their affective attachment to the community, leading them to intervene even when residents will not. Second, sanctions by police carry a threat of force generally not available to residents. The threat of arrest or violence is not as easily ignored as verbal sanctions from residents. Because residents may invoke police—and the role of officer carries an obligation to act and a legal capacity to use force—their informal sanctions be reinforced by the implicit threat of escalation.

### Mechanisms for Broken Windows

Informal social control is the primary mechanism which constrains crime and disorder, and it does so directly through the sanctioning of offenders and indirectly through the threat of sanctions--deterrence. The suggestion that police can support informal social control efforts suggests similar mechanisms are at work when police—rather than residents—are agents of social control. Further, it suggests the effect of sanctions or threats of sanctions from residents is in part dependent on the perception that residents can escalate to invoking police if their informal sanctions are rebuffed. Chapter \@ref(formalcontrol) of this dissertation examines these relationships at the neighborhood level.

In contrast to collective efficacy, broken windows is explicitly a multilevel model with articulated micro-level and inter-level mechanisms. In the direct mechanism, disorder reduces the perceived risk of sanction for offending and thus increases the likelihood of offending. This occurs because potential offenders interpret the presence of disorder to signify residents are unable or unwilling to intervene to regulate public space—disorder represents an indicator of criminal opportunity. If residents will not intervene against disorder, they are unlikely to intervene against serious crime as well. From the perspective of the offender, this can be seen to represent a general deterrence mechanism: If others were not been sanctioned for their past behavior, I will not be sanctioned for my future behavior. This pathway is a multilevel mode: Pervasive disorder in the neighborhood (macro condition) reduces perceived risk of sanctions (macro-micro transition), resulting in increased offending (micro-mechanism), which increases the crime rate (micro-macro transition). Evidence connecting disorder to individual offender perceptions of sanction risk is weak [@st.jeanPocketsCrimeBroken2007]. Evidence is stronger that neighborhood disorder—particularly social disorder—is associated with crime rates net of social control capacity [@lanfearBrokenWindowsInformal2020]. Where mechanisms are considered, this research suggests disorder may operate through crime-specific opportunities presented by some forms of disorder, rather than general reductions in perceived sanction risk [@lanfearBrokenWindowsInformal2020].

While not a primary focus of the theory, broken windows also includes a within-individual or within-group behavioral escalation mechanism. If children are rowdy and no one scolds them, their rowdiness will increase in response. If teenagers loiter and are not dispersed, it leads to fighting and accumulation of litter. If the signaling mechanism operates through a general deterrence mechanism, this is the corresponding specific deterrence mechanism: If I was not sanctioned for my past behavior, I will not be sanctioned for my future behavior. If we assume actors are approximately rational—as suggested by broken windows—and the perceived probability of sanction is positively related to the severity of the violation, then we would expect unchecked behavior to result in escalation due to updating of the perceived risk of sanctions. This is consistent with Bayesian updating in a rational choice model of offending [@matsuedaDeterringDelinquentsRational2006]. This is also suggested in collective efficacy research as a mechanism by which resident interventions against minor crime and deviance translate into reductions in serious crime: control and removal of contexts which may escalate to violence, such as youth loitering on the street [@sampsonGreatAmericanCity2012, p. 918; @sampsonNeighborhoodsViolentCrime1997a, p. 152].

In the indirect mechanism, disorder produces fear which reduces attachment to the community and causes withdrawal from public spaces, reducing neighborhood social control capacity. This occurs because residents also interpret the presence of disorder as an inability to regulate public space, and thus an inability to prevent serious crime. Because residents want to avoid having disquieting encounters or being victimized—rather than to victimize others—this perceived lack of regulatory capacity translates into fear which constrains social behavior.^[Harcourt [-@harcourtIllusionOrderFalse2001, p. 17] states broken windows implies different mechanisms for the "honest people" and the "disorderly people" in that disorder causes the "honest people" to withdraw or move out of the neighborhood and "disorderly people" to move into the neighborhood and commit crimes. This omits a key intervening mechanism based on meaning: in broken windows theory, everyone interprets widespread disorder to indicate social control is weak. What is different is not how disorder operates but how that meaning is translated into behavior by individuals. People behaving differently from the same stimuli does not necessarily indicate the stimuli is perceived differently, but rather may indicate different motivations. When not seeking to offend, a potential offender may also avoid places that appear unregulated to minimize their likelihood of victimization.] Note that in broken windows fear is not just about being a victim of serious crime like robbery but also about being confronted by unpredictable people [see also @innesSignalCrimesSignal2004]. Fear, here, is about the belief that public spaces are unregulated and a source of worrisome, potentially dangerous, encounters. The constrained social behavior which results from fear may be seen as a self-protective behavior which reduces the risk of personal victimization at the cost of increasing the risk to others [@bellairInformalSurveillanceStreet2000]. In this way, reduced social control may be seen as an externality arising from individually rational behavior . Important also is that the threat posed by a given situation is conditioned by individuals’ perceived vulnerability. An "obstreperous youth" may be perceived as a nuisance to an able-bodied adult man but a serious threat to an elderly one—physically vulnerable people are thus likely to be more sensitive to disorder as signals of danger [@innesSignalCrimesSignal2004], and thus more likely to constrain their behavior [@wilsonBrokenWindows1982].

Both attachment and use of public spaces are influenced by this fear. Fearful residents avoid others and restrict their activity spaces to home, safe locations, and the safest available routes between these locations. This reduces informal surveillance capacity—eyes on the street [@jacobsDeathLifeGreat1992]. The perception that the neighborhood is unregulated alienates residents as well, reducing attachment and thus the perceived responsibility to intervene even in the restricted areas they use—analogous to inhibiting expectations for social control in collective efficacy. This pathway represents another multi-level model: Pervasive disorder in the neighborhood (macro condition) produces fear in individuals (macro-micro transition), resulting in constrained behavior (micro-mechanism), which inhibits the collective capacity for social control (micro-macro transition). While not explicit in the original broken windows model, withdrawal likely also reduces informal social control by inhibiting formation and maintenance of social ties, and thus social capital, which foster community social control [@bursikNeighborhoodsCrimeDimensions1993]. Evidence for disorder reducing social control—including specifically via fear—is relatively strong [@lanfearBrokenWindowsInformal2020; see @obrienLookingBrokenWindows2019 for a counterpoint].

Importantly, the mechanisms in broken windows all operate through perception and interpretation. While rooted in objective conditions, the effects of disorder are mediated by people’s perceptions of the neighborhood as a whole. Individuals may see particular places or situations as dangerous—like where young men congregate—but the mechanisms of detachment and withdrawal are described as the result of seeing the entire neighborhood as an alien and dangerous place. This raises the question of how individual disorderly contexts and encounters translate into perceptions of the neighborhood—and, importantly, how perceptions of the neighborhood alter interpretations of particular situations. It does not follow from broken windows that disorder in one part of an otherwise orderly neighborhood will trigger the mechanisms at work. Disorder must be sufficiently pervasive or conspicuous to alter how the entire neighborhood is perceived.

In a related vein, Wilson & Kelling [-@wilsonBrokenWindows1982, p. 3] invoke perceptions of neighborhood norms:

>Because of the nature of community life in the Bronx—its anonymity, the frequency with which cars are abandoned and things are stolen or broken, the past experience of "no one caring"—vandalism begins much more quickly than it does in staid Palo Alto, where people have come to believe that private possessions are cared for, and that mischievous behavior is costly.

This passage suggests norms and expectations for social control matter in restraining crime—as in collective efficacy—but residents infer these from evidence of norm violations [see @st.jeanPocketsCrimeBroken2007]. Empirical evidence supports this position [@hippCollectiveEfficacyHow2016; @matsuedaMeasuringCollectiveEfficacy2016]. This could be interpreted as a separate normative mechanism [e.g. @harcourtIllusionOrderFalse2001] or another statement of general deterrence.

In contrast to collective efficacy, broken windows provides micro- and cross-level mechanisms linking social structural conditions to criminal situations. These mechanisms are based, however, on a relatively simple model of the actor that relies on uniform and unambiguous interpretations of disorder and other contexts. Evidence for these mechanisms is mixed [@lanfearBrokenWindowsInformal2020]. Broken windows (like collective efficacy) also neglects the role of other factors that influence criminal situations, such as variation in the availability of targets or the presence offenders. The next section describes routine activities theory, a macro-level theory which provides useful concepts and language for relating social structure to criminal situations.

## Routine Activities Theory

Routine activities theory describes an abstract model in which predatory crime results from the confluence of three necessary elements: suitable targets, likely offenders, and the absence of capable guardians [@cohenSocialChangeCrime1979]. Because all three elements must be present at the same time and in the same place for these crimes to occur, rates of such crimes will change whenever the joint distribution of these elements changes in society or a community. Rooted in Hawley’s [-@hawleyHumanEcologyTheory1950] theory of human ecology, routine activity theory is a population-level theory focused on direct-contact predatory violations that feed on the legitimate routine activities of the general population. Direct-contact predatory violations are defined as individual criminal incidents, "involving direct physical contact between at least one offender and at least one person or object which that offender attempts to take or damage," [@cohenSocialChangeCrime1979]. Mutually-culpable crimes like prostitution and drug sales or crimes without contact, like some financial crimes, lie outside its original purview, though later work has extended its reach [e.g. @clarkeRoutineActivityRational2004].

The focus of this theory is on how spatiotemporal organization of routine human activities translates criminality—regardless of its underlying source—into criminal actions. Because the joint distribution of offenders, targets, and guardians is determined by the patterning of legitimate routine activities in people’s lives—where and how they work, recreate, shop, etc.—it is possible for large changes in crime rates to occur without shifts in the motivation or number of likely offenders—such as when guardianship is impaired or targets are made more attractive. Simply put, provided the same potential offenders, more crime will occur when crime is easier to commit. For example, @cohenSocialChangeCrime1979 illustrated that increases in overnight and out-of-town travel (impaired guardianship) corresponded to similar increases in residential burglary, and reductions in the weight of consumer electronics (increased target attractiveness) corresponded to increases in electronics theft. These occurred despite little change in conventional structural causes of criminal motivation such as poverty. This sits in contrast with models like classic social disorganization that specify crime as the result of structural disadvantage and social breakdown. Changes in routine activities due to improvements in quality of life—such as increased leisure time and superior consumer goods—may increase crime as well. 

## Likely Offenders

In routine activity theory, a likely offender is defined as an individual with criminal inclinations and the capability—proficiency or tools—to carry out those inclinations. Using the ecological metaphor, likely offenders are treated as a distinct population that uses predatory means to gain sustenance from the environment. The source of criminal motivation or criminality—long the primary focus of criminology—is taken as given. In doing so, routine activity theory de-emphasizes offenders and focuses on the undertheorized elements: suitable targets and capable guardians. A key insight of routine activity theory is that a great deal of variation in crime can be explained without concern for the sources of criminality itself. This represents a theoretical separation of the criminal involvement or participation (criminality) from criminal events (crime), also a key element of the criminological rational choice perspective [@clarkeRoutineActivityRational2004; @cornishReasoningCriminalRational1986]. Empirical research using routine activity theory typically assumes the distribution of likely offenders is related to structural conditions such as socioeconomic disadvantage [@cohenSocialChangeCrime1979] or equivalent to population density by assumption of invariant motivation [@wilcoxCriminalCircumstanceDynamic2003]. Further, because routine activity theory is agnostic to the source of criminality—likely offenders—it may be explicitly integrated with most theories of criminality—whether individual level, such as control theory [@felsonRoutineActivitiesSocial1986] or rational choice [@clarkeRoutineActivityRational2004], or macro-level, such as social disorganization [@wilcoxCriminalCircumstanceDynamic2003].

## Suitable Targets

In routine activity theory, a suitable target is a person or property with some spatial and temporal location and which may be subject to harm or removal. Targets differ by their material or symbolic value (including liquidity), their visibility to and ease of access for likely offenders, and their resistance to the crime in question (e.g. size, weight, defensive capability). For a likely offender intending to profit by theft, the most suitable targets are thus expensive, portable, easily resold objects left in the open. Note that elements of suitability may be in conflict: For a likely offender interested in obtaining status gains through violence, a more difficult—that is resistant or dangerous—target may be attractive as that difficulty is entangled with their symbolic value as a target [e.g., @andersonCodeStreetDecency1990]. Operationalizing suitable targets (as well as the other elements) for expressive or mutually culpable crimes is thus challenging. Note also that potential victims (whether a target or owner of a target) may take evasive actions—which influence visibility, access, or resistance—to reduce the possibility of victimization, which may lead offenders to choose other targets.

### Absence of Capable Guardians

The final necessary component of a predatory crime is the absence of a capable guardian. There are many potential guardians that might prevent an act, and they may accomplish this via either intentional (e.g. sanctioning, calling police, active surveillance) or unintentional activity (e.g. passive surveillance). In this way guardianship, "links seemingly unrelated social roles and relationships to the occurrence or absence of illegal acts," [@cohenSocialChangeCrime1979, p. 590]. Later elaborations of routine activities introduced handlers and managers as additional social control agents. These additions specify clearer roles for certain actors. Handlers are actors with intimate affective ties to potential offenders. Drawing on control theory, it is assumed that a potential offender will be restrained from committing an offense if doing so would jeopardize the affective tie [@hirschiCausesDelinquency2002]. Place managers are actors who, as a consequence of ownership or being an agent of the owners, have rights to regulate access to and behavior within a property. In this chapter, I use the term guardian to refer broadly to any actor occupying the role of a potential social control agent.

It can be difficult to a priori specify an individual as a guardian, unless they occupy a role with formal obligations regarding guardianship (e.g. police, security guards, retail employees). For crimes that target property—rather than individuals—it is at least unambiguous that the absence of any individuals, beyond a likely offender, constitutes absence of a capable guardian. Accordingly, the absence of capable guardians for burglary has been operationalized with aggregate time spent away from home [@cohenSocialChangeCrime1979]. For crimes that target individuals, such as robbery, time spent away from home may also increase victimization, but likely through supply of suitable targets rather than reduced guardianship.

### The Built Environment

The language of routine activities allows us to integrate a factor neglected in both collective efficacy and broken windows: the built environment. The built environment has long been recognized as a one of the most important predictors of crime [e.g. @jacobsDeathLifeGreat1992, @newmanDefensibleSpaceCrime1978, and @jefferyCrimePreventionEnvironmental1977] and is a key cause of heterogeneity in the distribution of criminal opportunities [@st.jeanPocketsCrimeBroken2007]. Just as crime is concentrated in particular neighborhoods, within neighborhoods crime is concentrated in particular criminogenic locations—hot spots [@shermanHotSpotsPredatory1989; @weisburdCriminologyPlaceStreet2012]. The locations of hot spots are largely determined by characteristics of the built environment [@st.jeanPocketsCrimeBroken2007; @wilcoxSituationalOpportunityTheories2018]. By structuring the routine activities of people, the built environment generates hot spots characterized by the repeated convergence in time and space of motivated offenders, suitable targets, and the absence of capable guardians [@brantinghamEnvironmentalCriminology1981; @cohenSocialChangeCrime1979]. Situational opportunity theories of crime—including routine activities—suggest that different built environment characteristics provide opportunities for different types of crime, governing not just where crime occurs but what crime occurs [@wilcoxSituationalOpportunityTheories2018]. 

### A Language for Integration

I argue that Cohen and Felson’s [-@cohenSocialChangeCrime1979] routine activity theory provides a unifying language for linking collective efficacy to broken windows and the built environment. By using this language, we can see how the disparate theories fit together, and identify compatible and competing hypotheses among specific theories. From within this model, collective efficacy focuses on how neighborhoods increase guardianship by strengthening informal social control. Again within this model, broken windows posits that disorder signals to offenders an absence of capable guardians and inhibits guardianship by causing residents to withdraw from public spaces [@wilsonBrokenWindows1982]. Finally, within this model, the built environment dictates the suitability of targets and affects guardianship by revealing or concealing criminal behavior [@wilcoxSituationalOpportunityTheories2018].

This routine activities framework allows us to compare these theories. For example, it reveals that, beyond the mechanism of collective efficacy, communities can also control crime by keeping out likely offenders, hardening or removing targets, and calling on other guardians. Two methods for accomplishing these are altering the built environment and mobilizing law enforcement. Rather than intervening against individuals, communities may organize to eliminate contexts that attract offenders or conceal criminal acts from guardians—like rowdy bars or abandoned buildings, forms of disorder which provide criminal opportunities. Residents also use law enforcement to address crime and disorder through calls for service and demanding increased patrols or targeting of hot spots. The empirical chapters of this dissertation examine how neighborhoods regulate features of the built environment which generate criminal opportunities, and how perceived legitimacy and effectiveness of police relate to crime and collective efficacy.

### The Situational Micro-Model of Routine Activities

Research using routine activity theory is usually concerned with aggregate variation in crime rates that result from variation in the joint the distribution of elements of criminal events. For example, if consumer goods get lighter and smaller, there will be more thefts of consumer goods, or if people spend more time away from home, more houses will be burglarized and more people will victims of street crime [@cohenSocialChangeCrime1979]. In these applications, routine activity theory is typically treated as an additive model, despite its focus on crimes as convergences of elements. In an additive model, isolated increases or decreases in individual elements of crimes results in independent differences in the crime rate. In the aggregate, due to the large number of potential convergences, additive models describe the distribution of crime well—particularly those with logged outcomes [e.g., @cohenSocialChangeCrime1979, p. 604]. Despite its macro-level focus and additive applications, it is important to emphasize routine activity theory features an explicitly multiplicative micro-level model of criminal events. In a given situation, the absence of any element is sufficient to prevent the realization of a criminal incident. That is, crime cannot occur where there are no likely offenders, regardless of the number of suitable and unguarded targets. Elaborating routine activity theory in terms of its micro-model both extends the theory to smaller units of analysis and raises new problems for theorizing about situational determinants of crime.

First, crime is highly concentrated in space and time [@brantinghamEnvironmentalCriminology1981]. Routine activity theory may address this by drawing attention to the spatial and temporal patterning of individual convergences in targets, offenders, and guardians. To do this, however, we must consider the multiplicative (interactive) micro-model upon which the macro-level framework is constructed, and consider how, mechanistically, the micro-model relates to the macro-model. For instance, at the city or neighborhood level, more people on the streets may translate into more robbery because they serve as suitable targets. It does not follow, however, that in a specific situation, more people on a given street at a given time translates into a higher probability of robbery. The situation is dominated by interaction effects: A person alone may be a target, but additional people may serve as capable guardians. As a result, a robber might seek out a location where there is sufficient foot traffic to provide targets but insufficient traffic to provide guardianship—or where inconsistent traffic periodically produces isolated targets [@st.jeanPocketsCrimeBroken2007, p. 156]. More people on the street may thus generate more opportunities in the aggregate, but only because their uneven spatial and temporal distribution produces individual situations conducive to crime. Heterogeneity within macro units, such as neighborhoods, may produce large variations in crime despite similar aggregate numbers of suitable targets, guardians, and likely offenders. As noted earlier, the built environment is a key source of this heterogeneity. For example, a single strip of bars and other venues for nightlife—which concentrate suitable targets when guardianship is impaired—might be the source of the majority of violent crime in a neighborhood. A situational micro-model of crime is incomplete if it does not take into account the objective physical characteristics of the built environment that generate criminal opportunities.

Second, a situational routine activity framework must consider more carefully the characteristics of actors—their roles, agency, and subjectivity. To begin, the distinction between roles can be ambiguous in a situation. A guardian or offender for one type of crime may be a target for another, and roles may be fluid, changing quickly within a situation. Roles are also problematic because they may be tautological in the micro-model. If two people are in the same location at the same time and one of them steals or damages an object, then by definition the other person is not a capable guardian. This is problematic because guardians are defined in terms of absence, and the three elements are necessary but not sufficient for crime to occur. In contrast, one cannot infer that a person who refrains from stealing an unguarded target is not a likely offender—the convergence of the offender, target, and lack of guardian does not require a crime to occur. This issue of tautology can be addressed by providing a clearer conceptualization of these roles and how they operate in situations. This requires reference to a theory of individual motivation and action.

Related to this point, routine activity theory focuses on convergences of actors in different roles generated by patterns of routine legitimate activities. This can underemphasize the agency of offenders who seek to generate these convergences and responses by potential targets who seek to minimize them. While some criminal opportunities are serendipitous (at least from the offender’s perspective), others are intentionally manufactured. Agency of offenders, guardians, and potential targets is particularly important in a situational model of crime, because it produces selection into situations. For example, the broken windows mechanism by which fear of victimization produces withdrawal from public represents a process of self-selection out of routine activities in which the actor may serve as a target—and, unintentionally, also those where they might serve as a guardian. Strategic maximization or minimization of criminogenic convergences is itself a component of routine activities. In this way, individuals’ perceptions of criminal opportunities shape their routine activities.

Finally, routine activities theory focuses on objective characteristics, rather than subjective characteristics as perceived by actors. This is a not problematic if the differences between perceptions and objective conditions wash out in the aggregate—that is if subjective and objective opportunities converge over time as is commonly assumed in rational choice models. The central role of individual and shared perceptions—and their divergence from objective characteristics—in both collective efficacy and broken windows theories suggest this may not be the case. In situations, perceived opportunities become more important than objective ones, though they are tethered together.

## A Micro-Theory of Social Interaction Between Offenders, Targets, and Guardians

These prior points may be addressed with a micro-theory which takes into account individual perception and motivation, but also centers action in terms of interactions between actors and objects in a situation. This section draws from Matsueda and Lanfear’s [-@matsuedaMicroTheoryCrime2021] working paper which develops a situational micro-theory of criminal opportunity based on prior criminological work by [@giordanoGenderCrimeDesistance2002; @matsuedaCriminologicalImplicationsThought2006; @matsuedaReflectedAppraisalsParental1992] and the writings of American Pragmatists [@deweyHumanNatureConduct1922; @meadMindSelfSociety2015]. Following [@matsuedaMicroTheoryCrime2021], I address the role of perceptions of opportunity, the sources of motivation for actors, and the importance of the meaning of objects. While testing this situational explanation of crime is beyond the scope of the present dissertation, I discuss implications for specification and interpretation of statistical models. 

This situational explanation begins by treating motivated offenders, suitable targets, and capable guardians as distinct categories which correspond to social roles. These roles come with expectations, obligations, and norms that guide individual behavior and govern interaction between individuals occupying different roles [@matsuedaMicroTheoryCrime2021, p. 2]:

>Motivated offenders tend to follow social norms of offending groups, with expectations to carry out certain crimes, and obligations to follow group norms, such as "Don’t run out on a companion." The ideal suitable target lives up to the term "suitable" by generally failing to navigate dangerous streets effectively [see @sharkeyNavigatingDangerousStreets2006], such as by avoiding hot spots, dark alleys, abandoned buildings, and suspicious groups of men. Capable guardians live up to the term "capable" by exercising the capacity to prevent crime through monitoring and to intervene adroitly when criminal acts begin. For example, guardians may be residents who surveil their neighborhoods for signs of incivilities, and intervene when crimes occur by calling out the offender, physically intervening, seeking help from others, and calling the police.

As @matsuedaMicroTheoryCrime2021 note, actors vary in in the degree to which they are motivated to offend, suitable for victimization, and capable as guardians. These characteristics are in principle measurable before actors enter a situation, and could be used to predict the resolution of a situation. @matsuedaMicroTheoryCrime2021 argue this is an overly simplistic view of the situation because all social interactions, including those involving crime, feature an element of emergence [@matsuedaCriminologicalImplicationsThought2006; @mcgloinWhenCrimeAppears2012; @meadMindSelfSociety2015]. Actors enter situations with a particular objective, but this objective is reshaped through interaction with other actors in the situation [@meadMindSelfSociety2015]. @luckenbillCriminalHomicideSituated1977 illustrates this with an analysis of homicides, in which actors with the goal of saving face escalate conflicts into lethal violence. In this way actors may enter a situation taking a particular role, but through the process of interaction, come to assume another role.

The meanings actors attribute to people, actions, and situations are important components for a theory of criminal opportunity, because objectively identical situations may be defined in different ways by different individuals [@matsuedaMicroTheoryCrime2021, p. 5]:

>For a law-abiding person with little criminal motivation, an unguarded open cash register would mean that someone should alert a sales clerk of a potential problem; for a motivated offender, it would mean that they could steal money with impunity.  In other words, what is important is not just the objective opportunity, but rather the opportunity as perceived by the individual, which is based on a priori meanings actors bring into the situation, which are then shaped by the ongoing social process.  In a situation of crime, when a security guard is present, offenders are likely to interpret the guard as a capable guardian, and consider the increased risk of detection.

An advantage of taking a pragmatist position is that it emphasizes socially-derived meanings that shape situational behavior. What courses of action are considered as valid solutions—both in terms of action and result of that action—and what is interpreted as problematic in the first place depends on socially-constructed meanings acquired over the life course, in particular through social interaction with others, which is structured by membership in groups.

@meadMindSelfSociety2015 explains how membership in groups influences individual behavior—social control—with a dual-process model of cognition similar to later developments in cognitive psychology [@kahnemanThinkingFastSlow2011; see also @goffmanRelationsPublicMicrostudies1972, p. 241] . In this model, most behavior is habitual and non-reflective, and occurs in institutionalized settings. Cognitively taxing reflective decision-making is reserved for problematic situations where habitual responses fail to produce expected or desired results. When this occurs, individuals engage in an iterative process in which they consider alternative lines of action by taking the role of others, which may be actual individuals or generalized others representing entire groups with corresponding norms, expectations, and obligations [@matsuedaMicroTheoryCrime2021, pp. 6-7]:

>For example, a member of a delinquent gang may be the driver as well as lookout, and when confronted with a capable guardian, may take the role of the organized gang, consider expected behavior of the role, and consequently, warn the other members of the heightened risk.  Seeing the driver, the capable guardian may take the role of the community watch group and consider calling watch leader about the suspicious activity.  Thus, role-taking entails taking the role of reference groups, locating their role vis-à-vis other group roles, in solving problematic situations.  Note that role-taking entails taking the role of reference groups, which can be organized for crime (e.g. the delinquent gang) or against crime (e.g., the community watch) [@matsuedaDifferentialSocialOrganization2006].

Once a problematic situation is resolved, actors incorporate the experience into the self and may use it as a guide for future behavior. As each actor enters the situation with a different self, they also take away different meanings from this experience. This process of updating the self through experience creates individual continuity and change, and, importantly, also produces shared social meanings and ultimately group social control [@matsuedaMicroTheoryCrime2021, p. 7]:

>The shared nature of experience gives rise to shared meanings, which helps to account for continuity in selves and behaviors within interaction groups.  When members of a group consistently interact with each other and create or negotiate shared meanings, group identities emerge from the commonality of individual selves.
> 
>The mechanism of social control, then, is self-control, in which the self—which begins with the cumulative sum of previous experiences derived from social groups and communication networks, is updated through social interaction, and influences behavior through habitual behavior and the cognitive process of role-taking [@matsuedaDifferentialSocialOrganization2006].

@matsuedaMicroTheoryCrime2021 note two empirical implications of this perspective which are particularly relevant to the present framework. First, in stable, institutionalized settings, thinking is habitual and non-reflective and meanings are stable. Stable institutionalized settings may include neighborhoods high in collective efficacy—but also those with a strong code of the street [@andersonCodeStreetDecency1990]. Norms and expectations for behavior are clear in both settings, at least for those enmeshed in local networks. Outsiders and those unaware of shared meanings may suffer consequences for violations of expectations, which may lead to rapid uptake of these shared meanings. This may contribute to the stability of these shared meanings, and thus social structures of the neighborhood, over time. These stable social meanings provide a mechanism for the regulation of group member behavior to realize collective goals—Janowitz’s [-@janowitzSociologicalTheorySocial1975] definition of social control.

Second, in novel situations, habits break down, actors engage in role-taking, and new meanings evolve which become available for individuals in similar future situations. Novel situations may occur as the result of an actor entering an unfamiliar location or encountering unfamiliar groups. They may also occur in familiar locations and among familiar groups when shared meanings become unstable. In broken windows theory, sudden increases in disorder destabilize norms and create fear of victimization. Here, habits which fostered effective social control, like unrestricted use of public spaces, give way to self-protective behavior, like avoiding public spaces. Gentrification may produce a similar destabilization, where unclear and conflicting expectations between newcomers and long-time residents lead to sanctioning or criminalization of previously acceptable behavior [e.g., @freemanThereGoesHood2006; @lanfearFormalSocialControl2018a].

### Identities and Dynamics of Motivated Offenders, Suitable Targets, and Capable Guardians

As @matsuedaMicroTheoryCrime2021 describe, actors occupying each of the roles of routine activities enter situations with stable but multidimensional self, composed of a unique history of past interactions (situations) and different overlapping reference groups (generalized others):

>The selves, then produce habitual behavior in institutionalized settings and enter into cognition via role-taking in problematic situations.  Symbolic interactionists use the term role-identities to emphasize that selves correspond to roles within a generalized other, and specify that identities vary across different dimensions such as commitment and salience [e.g., @mccallIdentitiesInteraction1978, @strykerSymbolicInteractionismSocial1980, and @heimerRoleTakingRoleCommitment1994], and the interaction between the two.

Variation in commitment and salience of identities—as potential offender, target, or guardian—influence role-relevant behavior [@matsuedaMicroTheoryCrime2021]. Offenders with salient criminal identities and commitment to criminal roles will participate in a wide variety of offenses and offend in many situations. Those with less salient identities and weaker commitment will be easily deterred. Potential targets may develop identities as wary and streetwise, using experience and knowledge to avoid being a suitable target and effectively avoid or navigate dangerous situations. Those who do not learn protective behaviors are more likely to be victimized should they encounter motivated offenders. Objects can be suitable targets as well, and owners often purposefully imbue them with crime-relevant meanings using visible protective features to reduce their perceived suitability. When these features are common in a place, it changes the meaning of objects that are unprotected: they stand out as vulnerable targets. Guardians also vary in salience and commitment to their role based on factors like trust in and attachment to neighbors [e.g., @sampsonNeighborhoodsViolentCrime1997a], but also by the nature of the crime or its target [e.g., @eckPlaceManagement2018b]. Collective efficacy may directly capture respondents’ identification with the role of guardian by measuring their expectations for social control behavior by their neighbors—the generalized other of a group to which they belong. Formal guardian roles, like being a police officer, are likely accompanied by strong salience and commitment [e.g., @wilsonBrokenWindows1982].

These roles of motivated offender, suitable target, and capable guardian are abstractions and distinct only analytically. For individuals in real situations, roles may be fluid, changing as the situation develops. For example, Anderson’s [-@andersonCodeStreetDecency1990] code of the street depicts "street" youth as immersed in a violence-based status system which is a cultural adaptation to concentrated disadvantage. These youth sit in the precarious circumstance of being a likely, motivated offender seeking status gains by victimizing other youth, but highly sensitive to the possibility of being a target for the status gains of others. They may embody the role of offender and initiate an altercation if they perceive the situation is in their favor, such as in a chance encounter with a situationally vulnerable target. If the tables are turned, and they perceive themselves as vulnerable to victimization, the role of target becomes salient, and they may seek to avoid conflict or deescalate. The dynamics of interactions among actors may produce unanticipated emergent outcomes, perhaps outcomes undesirable to all involved, such as when a need to save face locks actors into mutual escalation with violent consequences [@luckenbillCriminalHomicideSituated1977]. In this example, the cultural frame of the code of the street leads actors to take the roles of motivated offender or suitable target, and additionally conditions the emergent properties of the situation.

The above example also highlights that each role of the actor exists both as an image of the self and as an image of others. Both are consequential for behavior because the meanings carry with them expectations for behavior. For example, collective efficacy reflects residents’ expectations that their neighbors (a reference group to which they belong) will take the role of guardian and intervene against deviance in public places [@sampsonGreatAmericanCity2012]. Prior to intervening, a resident may not view themselves as a guardian, but elements of the situation—such as the presence of an actor they interpret as a potential offender—may lead to the activation of the role. Residents who intervene do so because they perceive themselves as a guardian and those they intervene against as an offender.

Similarly, the code of street creates in actors the expectation that "street" people will be motivated offenders and, importantly, that one can reduce the likelihood of becoming their target by projecting the image of being a motivated offender yourself [@andersonCodeStreetDecency1990]. This highlights that an actor takes purposeful protective measures as a result of taking the role of a suitable target, imagining their potential victimization and choosing a course of action they believe will prevent it or minimize harm [e.g., @st.jeanPocketsCrimeBroken2007, p. 156]. For this reason, offenders seek out naïve individuals that do not perceive themselves as suitable targets, and thus do not take protective actions [e.g. @deakinTaxingStreetsUnderstanding2007; @st.jeanPocketsCrimeBroken2007]. 

### Selection into Situations

An analysis of interaction in situations is conditional on individuals selecting into the situation. Consequently, a situational theory is incomplete without a theory of selection into criminogenic situations [@matsuedaMicroTheoryCrime2021]. The same micro-theory of the individual described above may be applied to the selection process. Rather than asking how roles relate to individual behavior within a situation, one can move to the preceding step and ask how roles relate to individuals entering particular situations. Here I also raise the built environment as an important determinant of selection into situations.

If motivated offenders have the goal of maximizing successful offending, then they will select into situations with few guardians and many targets. Research on offender decision-making suggests offenders engage in both passive and active search processes [@cornishReasoningCriminalRational1986]. In the passive search process, the offender is engaged in non-criminal activities during their daily round, but may recognize and take advantage of perceived criminal opportunities they encounter. It is also possible that actors with stronger salience and commitment to the offender role may be more exposed to certain opportunities. In the active search process, the offender seeks out or creates situations where they can engage a suitable target in the absence of guardians. In St. Jean’s [-@st.jeanPocketsCrimeBroken2007] interviews of active offenders in Chicago, offenders reported their active search processes were determined by favorable built environment characteristics, past offender successes, reputations of locations, and, for drug dealing, legitimate uses of space that provide plausible deniability and access to customers. These findings are supported by other research on offender decision-making [e.g., @cornishReasoningCriminalRational1986].

It is presumable that most actors want to avoid becoming victims of crime. Actors who recognize themselves as suitable targets should attempt to select into situations with many guardians and few offenders. An important aspect of selection for targets is that it is likely to be a secondary concern existing mainly in relation to other primary activities. That is, actors aware of the potential for victimization balance perceived risk against other goals they want to accomplish. At one extreme, actors who do not recognize themselves as suitable targets will be unconcerned with the potential for victimization and unconstrained in where they go and what they do (at least with regard to crime). These actors form the ideal suitable target [@deakinTaxingStreetsUnderstanding2007]. At the other extreme, actors putting victimization above all other concerns will, if possible, not even leave the safety of home [e.g., @wilsonBrokenWindows1982]. Most people lie somewhere between these extremes, avoiding what they perceive to be high risk situations while engaging in a daily round that satisfies their needs for sustenance and leisure. Variation in exposure to risk is a primary mediator linking sociodemographic characteristics of individuals to rates of victimization [@hindelangVictimsPersonalCrime1978].

Motivations for guardians—and thus their selection into situations—is complicated by wide variation in actors who might assume the role of guardian. The police and security guards, for instance, have a clear motivation to select into criminogenic situations to maximize their ability to prevent crime and apprehend offenders. Other guardians with formal roles include owners and employees whose guardianship is closely connected to a particular business and perhaps the surrounding area [@eckPlaceManagement2018b]. Their selection into situations is governed mainly by other concerns—the regular operation of the business. Some actors who may otherwise be considered offenders may select into some situations as guardians. For example, @titaImpactGangFormation2007 find gangs defending their turf provide guardianship against rival gang members and robbery offenders. For potential informal guardians, such as people at home or on their daily round, selection into situations where they serve as a guardian may often be unintentional—unless intertwined with concerns over being a suitable target, such as staying home if concerned about burglary or joining a neighborhood watch patrol when worried about rising neighborhood crime rates.

The built environment is an important determinant of selection into criminogenic situations. Locations of employment, amenities, and services—grocery stores, banks, schools, parks—have physical locations. The daily rounds of people require that they visit these locations and also travel through locations between them. Even if a particular location is perceived to pose a high risk of victimization, actors may still select into that location because they need what is provided at that location and they have limited alternatives. Motivated robbery offenders take advantage of the need for suitable targets to visit particular locations, especially those attracting customer carrying cash and other values [@st.jeanPocketsCrimeBroken2007]. Motivated offenders may also select into locations which have few legitimate uses, like vacant lots and abandoned buildings, as they can be used to conceal illicit transactions and objects like firearms from capable guardians [e.g., @macdonaldChangingPlacesScience2019]. Chapter \@ref(builtenvironment) of this dissertation examines a response to this form of selection: When residents recognize particular places as generators of criminal opportunities, they may organize to remove them, thus eliminating that context as a possibility for actors to select into.

### Empirical Implications for Macro-Analyses

In this final section, I consider three sets implications for macro-analyses of crime derived from the situational perspective, specifically those related to differences between perceived and objective opportunities, macro-micro mechanisms, emergence, and micro-macro mechanisms.

#### Perceived versus Objective Opportunity

The empirical chapters of this dissertation feature analyses of data aggregated to the block and neighborhood level, in particular objective measures of opportunity. This chapter, in contrast, focuses on the situation, and posits that opportunities perceived by potential offenders are a key determinant of outcomes in potentially criminal situations. An important question is, how are perceived opportunities related to objective opportunities? @matsuedaMicroTheoryCrime2021 suggest three possibilities, each with consequences for models at the macro level: (1) perceived and objective opportunities may be perfectly correlated, in which case macro-analyses regressing crime on objective opportunities will produce unbiased estimates; (2) perceived and objective opportunities may be unrelated—which is highly unlikely—in which case macro-analyses regressing crime on objective opportunities will on average find no relationship; or (3) some potentially complex process relates objective opportunities to perceived opportunities. For example, perceived opportunities may be updated in a Bayesian fashion based on new information, resulting in more accurate perceptions for more experienced actors [@matsuedaMicroTheoryCrime2021; see also @matsuedaDeterringDelinquentsRational2006].^[That actors update their perceived opportunity based on experience does not guarantee that perceived opportunities converge toward objective opportunity over time. For example, @oppLimitedRationalityCrime1997 suggests that in contexts where objective opportunity is high but perceived opportunity is low, updating may not occur because offenders will not attempt crime. Conversely, where perceived opportunity is high but objective opportunity is low, updating will happen quickly because offenders will be sanctioned with high certainty. Asymmetrical updating may provide a mechanism by which high collective efficacy neighborhoods maintain low crime rates absent interventions if, regardless of objective opportunity, perceived opportunity is so low that offenders are deterred absolutely [e.g., @sampsonGreatAmericanCity2012]. If this is true, it presents the interesting possibility of a fragile equilibrium. If both residents and potential offenders base their estimation of high collective efficacy (and thus low opportunity) on the absence of crime, despite the actual capacity for control being weak, the neighborhood may be vulnerable to an information cascade in which a successful offense reveals greater than expected opportunity, which induces further offending, and so on, causing both an increase in crime and a drastic reduction in perceived collective efficacy.]

If this third possibility is true it may violate an assumption of macro-models of criminal opportunity. Aggregate studies of criminal opportunity focus on variation in objective opportunities as a cause of variation in rates of crime [e.g., @cohenSocialChangeCrime1979]. These studies implicitly assume differences between perceived and objective opportunities "wash out" in the aggregate. If the correspondence between perceived and objective opportunities is imperfect, the effect of opportunity on crime will be underestimated. Further, if this correspondence varies across actors, groups, and geographies, then estimated effects of differences in the distribution of objective opportunities will be conflated with differences in the distribution of meanings relevant to the perception of opportunity.

Relaxing the assumption of correspondence between perceived and objective opportunity in macro-analyses could be approached either by directly measuring perceived opportunities or by using membership in groups as a moderator for objective opportunities. These approaches are complementary, as measures of perceived opportunity may be used to identify group differences in the divergence between perceived and objective opportunity. @matsuedaMicroTheoryCrime2021 hypothesize that perceived and objective opportunities will be strongly correlated in homogenous groups in highly-institutionalized criminal contexts and weakly correlated in heterogeneous groups in novel situations. Appendix \@ref(bemoderation) tests whether collective efficacy—which, when high, may reflect a highly-institutionalized but non-criminal context—moderates the effect of built environment features on crime. I find weak evidence for this moderation effect.

#### Macro-Micro Mechanisms and Emergence

Social structural theories of neighborhood crime imply differences in outcomes of situations across groups and neighborhoods. Otherwise identical configurations of motivated offenders, suitable targets, and capable guardians are expected to yield different situational outcomes based on the context of these social structural features. This represents a macro-micro link in which these social structural features make certain outcomes more or less likely to occur—such as promoting or discouraging violent escalation—by patterning norms, expectations, and resulting habitual behavior.

The framework on police efficacy presented in Chapter \@ref(formalcontrol) provides an example. I hypothesize that in a neighborhood where the police are perceived as efficacious, motivated offenders are more likely to be deterred by the threat of sanctions by residents, because they recognize the potential for the resident to escalate the confrontation by invoking the police. The same offender might ignore the sanction or retaliate against the same guardian in a context where police are collectively viewed as less efficacious. I test this contextual effect at the aggregate level by predicting crime using an interaction between police efficacy and collective efficacy, and find modest evidence for a multiplicative protective effect. A stronger test could be made using data on risk perceptions of (potential) offenders, or perhaps using vignette experiments that test the effect of informal control on willingness to offend while manipulating perceived police efficacy.

Beyond impacting what occurs in situations by structuring habitual behavior, differences in social structure may pattern situational emergence [@matsuedaMicroTheoryCrime2021]. Emergent effects arise when interactions between actors result in outcomes that are not predictable given their individual biographical histories. If criminogenic emergence is non-randomly distributed across aggregate units, it may induce bias in models which assume the outcomes of situations are a function only of the characteristics of actors (whether additive or multiplicative). Similar to differences in perceived and objective opportunity, @matsuedaMicroTheoryCrime2021 hypothesize that emergent properties should be minimal where actors or homogenous and interactions are institutionalized and habitual. Among heterogenous actors and in novel situations, interaction processes will generate unexpected outcomes. If this is true, the degree of emergence in situations will be related to community social structure. Forms of community social organization which promote institutionalized interactions—whether pro-crime or anti-crime [@matsuedaDifferentialSocialOrganization2006]—will generate more predictable situational, and thus aggregate, outcomes. Emergence may also be consequential where neighborhoods diverging in social organization border one-another. Even if these neighborhoods are relatively homogenous internally, mobility across porous borders may generate novel interactions between heterogenous actors. This will result in emergent properties dependent on the overall spatial patterning of neighborhood social structural characteristics.

#### Micro-Macro Mechanisms

Just as shared meanings may influence what occurs in situations, what occurs in situations contributes to shared meanings. For example, the code of the street represents shared meanings that govern how situations involving status conflict unfold, but those shared meanings were established through the accumulation of direct and vicarious experiences of status conflict in the past. When new situations involving status conflicts unfold as participants and observers expect them to, based on their shared understanding of the code of the street, it reinforces and propagates that shared meaning. If, however, these means of satisfying status conflicts are routinely disrupted, this shared understanding may be eroded over time.

Similarly, if a homicide occurs on a particular street corner of a low-crime neighborhood, that corner may take on a powerful shared meaning. This may alter behavior in the location where the crime occurred, such as if residents avoid that corner out of fear of victimization or engage in monitoring to prevent reoccurrence, or in similar locations elsewhere in the neighborhood. It is also possible the homicide will be taken as a salient event which alters perception of the entire neighborhood—from a place safe from violence to one where violence can strike without warning. This may alter behavior across the entire neighborhood. For example, @carrCleanStreetsControlling2005 describes a double homicide in a Chicago neighborhood as a salient event which changed resident perceptions of the neighborhood, resulting in mobilization against gang activity. In this way, the outcome of a single situation can have wide-ranging effects on the macro-context of a neighborhood.

Broken windows theory describes a similar micro-macro process in which individuals interpret instances of disorder as signals of elevated risk of victimization, and, as a result, select out of public spaces where they may be exposed to offenders [@innesSignalCrimesSignal2004; @wilsonBrokenWindows1982]. In theory, this produces effects on victimization which are opposite in sign at the micro- and macro-level. While the individual risk of victimization (micro) is reduced by constraining behavior, it increases the general risk of crime in the area (macro) by reducing the number of potential guardians in public spaces [@bellairInformalSurveillanceStreet2000]. This and the prior examples suggest complex multi-level dynamics which may be obscured in single-level and cross-sectional research designs.  Future research should explore these relationships using repeated observations of individuals nested in neighborhoods, ideally with independent data on crime.

## Conclusion

This chapter attempted to accomplish two related goals. In the first part of this chapter, I provided an overview of the theories used in the empirical chapters of this dissertation: collective efficacy, broken windows, and routine activities. While often treated as competing explanations for crime, these theories are largely complementary in their causal mechanisms. They also share a reliance on incompletely articulated micro-models of situations and individual behavior, in particular unexamined perceptual mechanisms. In the second part of this chapter, I proposed a framework for integrating these theories into a multi-level situational explanation for crime using a pragmatist micro-theory [@matsuedaMicroTheoryCrime2021]. The purpose of this framework is to specify the social mechanisms left unarticulated in these social structural theories. This framework draws attention to the importance of individual roles and meanings, selection into situations, and causal links between situations and macro characteristics of neighborhoods and groups. In doing so, it connects the macro-structural theories of neighborhood crime to a broader literature, including but not limited to, cultural explanations of violence [@andersonCodeStreetDecency1990], situational models of crime [@luckenbillCriminalHomicideSituated1977], criminal opportunity [@st.jeanPocketsCrimeBroken2007; @wilcoxSituationalOpportunityTheories2018], and perception and interpretation of disorder and crime [@harcourtIllusionOrderFalse2001; @innesSignalCrimesSignal2004]. 

While I propose situational mechanisms for neighborhood social structural characteristics, the present dissertation cannot test these mechanisms directly—though my findings are consistent with the theory presented. This chapter serves as a necessary first step of specifying social interactional mechanisms for a neighborhood theory of social structure and opportunity and considering their implications for empirical studies. The next step is clearly specifying propositions that arise from this framework and subjecting them to empirical tests.



