# Conclusion {.unnumbered}

This dissertation proposes an integrated multi-level theory of social structure and criminal opportunity. It also presents empirical tests of two sets of propositions related to this multi-level theory. In this closing chapter, I first review the key findings and implications of each chapter of the dissertation, then discuss future directions for research suggested by my theoretical framework and empirical results.

## Contributions

Chapter \@ref(theory) presents a detailed overview of key social structural explanations of crime and proposes an integrative theory based on situational social interaction. The primary contribution of this chapter is the specification of social mechanisms for these structural theories, which are presently underdeveloped. The proposed micro, micro-macro, and macro-micro mechanisms generate testable propositions to guide future macro- and multi-level research on neighborhood crime. The interactional social mechanisms present a secondary contribution by connecting collective efficacy, broken windows, and routine activities to cultural explanations of violence, situational models of crime, and perception and interpretation of disorder and crime.

Chapter \@ref(builtenvironment) proposes the built environment as a mechanism by which collective efficacy reduces crime, and presents an empirical test using block-level built environment data nested in Chicago neighborhoods. Results indicate collective efficacy negatively predicts built environment features like abandoned buildings and mixed land use, which, in turn, positively predict violence and property crime. This chapter makes two main contributions. First, it provides evidence for a macro-micro mechanism by which collective efficacy reduces incidents of crime. While evidence for the effect of collective efficacy on crime is relatively strong at the neighborhood level, the commonly proposed mechanisms that translate collective efficacy into fewer incidents of crime—such as informal control—are largely unobserved. Control of the built environment is a mechanism strongly support by research linking built environment features to criminal opportunity. These findings thus provide an observable mechanism for collective efficacy while linking it into the broad situational opportunity literature. Second, this chapter implicates collective efficacy in promoting the stratification of neighborhoods in physical quality. The built environment is an important predictor of the quality of life and wellbeing of residents. High collective efficacy may enable neighborhoods to accumulate beneficial features, while low collective efficacy neighborhoods accumulate harmful features that they lack the power to resist or remove. Thus, collective efficacy may promote neighborhood inequality by influencing the allocation of resources and development.

Chapter \@ref(formalcontrol) contributes to the literature on policing and collective efficacy by testing a strong and commonly-made assumption—that police efficacy promotes collective efficacy. It also proposes an alternative hypothesis: police efficacy strengthens the effect of collective efficacy on crime. This chapter tests these propositions using two waves of community survey data from Chicago in a variety of model specifications. In contrast to the existing literature, the results provide consistent evidence that police efficacy is descended from collective efficacy. Mixed evidence is found for the moderation hypothesis. The findings from this chapter have important implications for future research as well as policy. Studies that treat collective efficacy as a mediator for police efficacy may produce biased and misleading estimates. Similarly, interventions that attempt to bolster collective efficacy by promoting perceptions of police efficacy may be unlikely to yield the intended results. Additionally, protective effects of collective efficacy may be interrupted when exogenous factors suppress actual or perceived effectiveness and legitimacy of police.

## Future Directions

The first clear directions for future research are stronger and more comprehensive tests of collective efficacy and its mechanisms. The empirical chapters of this dissertation found weak effects of collective efficacy on crime. As our recent review concluded [@lanfearBrokenWindowsInformal2020], stronger tests of the effect of collective efficacy on crime are needed, in particular using longitudinal data and causal designs. Particular attention should be paid to uncovering causal mechanisms for collective efficacy—in particular actual methods of intervention. This could be accomplished by augmenting surveys with vignettes probing means of intervention or conducting field experiments that hold constant deviance and attempt to induce sanctions in neighborhoods varying in collective efficacy. An important question this research might answer is, how do the means of intervention differ across neighborhoods varying in collective efficacy—and possibly more importantly—economic advantage and racial composition? It is likely the mechanisms that translate collective efficacy into low crime vary across neighborhoods, such as in the use of mediating actors, a point I return to shortly.

The results of Chapter \@ref(builtenvironment) suggest the need for a deeper examination of the link between collective efficacy and the built environment. The built environment structures all human activity and consequently has wide-ranging impacts on individual and collective wellbeing. Collective efficacy may facilitate neighborhood stratification by impacting the ability of communities to attract, maintain, and compete for features of the environment that promote wellbeing. It is important that we understand how this occurs and what effects it has on neighborhoods and cities. This thread of research should consider the physical development of land over time as the result of a complex multi-level system relating local factors like crime, neighborhood wellbeing, the actions of residents—actions which include not just interventions but also residential mobility—and broad metro- and region-wide processes [e.g., @dreierPlaceMattersMetropolitics2014; @loganUrbanFortunesPolitical2007]. This calls for situating collective efficacy in a broader political economy framework, a worthwhile long-term goal for theoretical development in this area.

The results of Chapter \@ref(formalcontrol) call into question assumptions made about the role of police effectiveness and legitimacy in the neighborhood social control system: collective efficacy does not appear to be influenced by police efficacy. These findings suggest new directions for research. First, the causal ordering of collective efficacy and police efficacy has important implications for research and policy. Consequently, these results should be replicated in other settings and samples, ideally newly collected data, as the social context of policing has changed since the data used in this dissertation were collected. Second, the mechanisms linking collective efficacy to police efficacy are only speculative (e.g., more frequent resident interventions make policing fairer and more effective). Researchers should attempt to identify the mechanism in operation. This is likely to require collection of new survey data or interviews embedded in neighborhoods varying in collective efficacy and police efficacy. Third, both empirical research and theory on collective efficacy would benefit from disentangling formal social control from informal social control. While collective efficacy may capture a general capacity for intervention by residents, the consequences of these forms of intervention—as well as the factors influencing their relative use—are categorically different.

Both empirical chapters propose mechanisms for collective efficacy which require operating through mediating actors and organizations such as police and local government. This suggests theoretical extensions to collective efficacy—a focus on these mediating actors—and new directions for empirical research. Future research should interrogate the role of these actors in facilitating—or impeding—resident actions to address crime and perceived opportunities. The full range of actors and organizations efficacious residents engage to address different classes of problems is presently unknown. @einsteinNeighborhoodDefendersParticipatory2020 found residents were remarkably resourceful in efforts to combat developments like low income housing. It is reasonable to expect residents are similarly innovative in addressing crime and other social problems. Previously unconsidered means of intervention might provide mechanisms explaining collective efficacy’s broad effects on community wellbeing. We may also consider how changes in available means–new mediating actors—might alter resident behavior and outcomes such as crime and the built environment. For example, the availability of non-police responses—like community responder models @irwinCommunityResponderModel2020—might encourage resident interventions when invoking police is perceived as excessive or dangerous.

A related concern is how interventions that operate through these mediated actors and organizations impact individuals, neighborhoods, and cities. Broad literatures document the consequences of residents invoking police, which results in racial disparities in contacts and use of force, or influencing the built environment, which extends and maintains racial-residential segregation. As research uncovers new mechanisms for collective efficacy that operate through mediating actors, researchers must consider how the actions of those actors result in inequitable or harmful outcomes. Wilson and Kelling [-@wilsonBrokenWindows1982, p. 6] asked, if we empower police to respond as residents desire, "How do we ensure, in short, that the police do not become the agents of neighborhood bigotry?" Similarly, we must ask how representatives and agencies of local government can be responsive to residents without acting to "maintain the racial or ethnic purity of a neighborhood," [@wilsonBrokenWindows1982, p. 6]. This area of research is important for connecting collective efficacy to the broad literatures on political economy and urban inequality.

Just as the empirical chapters argue for extending collective efficacy upward to systems and processes operating at the level of the city, the theoretical chapter argues that future research should extend collective efficacy—and other social structural theories of crime—downward to individuals and the situation. While collective efficacy has been linked to many indicators of community wellbeing, there is presently no coherent framework that explains why these effects exist or where to expect to find similar effects. This is because most of the outcomes of interest in this literature manifest at the level of individuals or situations, but collective efficacy focuses on macro-level relationships with no clearly elaborated micro- or cross-level mechanisms. Collective efficacy theory tells us what to expect at the macro-level but does not explain why: it is a black box. Opening this black box is necessary for producing a complete explanation of how collective efficacy reduces crime—and, as this dissertation discussed, influences the built environment and effective policing. It is also important for determining how to manipulate collective efficacy, whether for policy or research, and address possible negative consequences [e.g., @lyonsCommunityDisOrganization2007]. Specification of mechanisms also facilitates linking collective efficacy to other social structural theories that imply similar micro-mechanisms (e.g., broken windows).

The first chapter of this dissertation is an initial effort at extending collective efficacy to the situation and integrating it to other theories of neighborhood social structure. The next steps for this effort are refining the theory and generating and testing propositions empirically. As with the suggestion to extend collective efficacy into a broad political economy framework, articulating a multi-level theory of the situation is a long-term, but worthwhile, goal.

## Coda

It is my hope this volume stimulates deeper thinking about neighborhood-level explanations for crime. The goal of this work is not to unnecessarily complicate collective efficacy theory—or broken windows, or routine activities—but rather to clarify. Clearly-specified theories with explicit mechanisms permit more convincing tests and accurate predictions. They also allow us to recognize similarities between disparate frameworks, bridging seemingly conflicting perspectives to develop more complete and satisfying explanations. Finally, understanding the social mechanisms that produce collective efficacy and translate it into neighborhood safety and wellbeing will imply interventions to improve conditions in the most disadvantaged neighborhoods--which should be the ultimate goal of neighborhood research.
